import { test, expect } from "@playwright/test";
import path from "node:path";
const out=process.env.FORGEFLOW_AUDIT_SCREENSHOTS;
test("health warnings and unavailable data are explicit on desktop and mobile",async({page})=>{
 await page.route("**/api/health/details",route=>route.fulfill({json:{status:"warning",checked_at:"2026-10-10T00:00:00Z",checks:[{id:"database",name:"Database",status:"ok",message:"Database connection responded."},{id:"temp_disk",name:"Temporary storage",status:"warning",message:"Less than 512 MiB is free. Free disk space before starting long tasks.",free_bytes:54*1024*1024}]}}));
 await page.goto("/settings");
 await expect(page.getByRole("heading",{name:"System health",exact:true})).toBeVisible();
 await expect(page.getByText(/Attention needed before long tasks/)).toBeVisible();
 await expect(page.getByText(/54 MiB free/)).toBeVisible();
 if(out)await page.screenshot({path:path.join(out,"health-desktop.png"),fullPage:true,animations:"disabled"});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(out)await page.screenshot({path:path.join(out,"health-mobile.png"),fullPage:true,animations:"disabled"});
 await page.route("**/api/health/details",route=>route.fulfill({status:503,json:{error:"unavailable"}}));
 await page.getByRole("button",{name:"Refresh checks"}).click();
 await expect(page.getByRole("alert").filter({hasText:"Health checks unavailable"})).toBeVisible();
 await expect(page.getByText(/Local checks passed/)).toHaveCount(0);
});
test("editing a PR draft prevents submission and renews approval",async({page})=>{
 const c={id:"draft-ui",repository:"fixture/addition",title:"Correct addition",state:"PR_PREPARED",branch:"autopilot/issue-1",config_version:1,demo:false,workspace:"S:/fixture/repo",base_commit:"a".repeat(40)};
 let r={status:"PR_PREPARED",summary:"Fixed addition",fix_iterations:0,review_cycles:1,network:false,review:{verdict:"APPROVE",summary:"Reviewed",findings:[]},diff:"",report:"Internal evidence",pr_title:"Fix addition",pr_body:"Regression tests passed. Fixes #1",pr_revision:"rev-one",submission_token:"approved-one",pr_url:""};
 await page.route("**/api/contributions",route=>route.fulfill({json:[c]}));
 await page.route("**/api/contributions/draft-ui",route=>route.fulfill({json:c}));
 await page.route("**/api/contributions/draft-ui/execution",route=>route.fulfill({json:r}));
 await page.route("**/api/contributions/draft-ui/tests",route=>route.fulfill({json:[]}));
 let saves=0,submits=0;
 await page.route("**/api/contributions/draft-ui/pr-text",async route=>{const body=route.request().postDataJSON();expect(body.revision).toBe("rev-one");saves++;r={...r,pr_title:body.title,pr_body:body.body,pr_revision:"rev-two",submission_token:"approved-two"};await route.fulfill({json:r})});
 await page.route("**/api/contributions/draft-ui/submit-pr",async route=>{expect(route.request().postDataJSON()).toMatchObject({approved:true,token:"approved-two"});submits++;await route.fulfill({json:r})});
 await page.goto("/contributions/draft-ui");await page.getByRole("tab",{name:"PR",exact:true}).click();
 const approve=page.getByRole("checkbox",{name:/I approve creating or using my fork/});const submit=page.getByRole("button",{name:"Submit PR to GitHub"});
 await approve.check();await page.getByRole("button",{name:"Edit PR draft"}).click();await expect(approve).toBeDisabled();await expect(submit).toBeDisabled();
 await page.getByRole("textbox",{name:"PR title",exact:true}).fill("Correct addition for negative operands");
 await page.getByRole("textbox",{name:"PR description"}).fill("Correct addition and cover negative operands.\n\nTesting: go test ./... (exit 0).\n\nFixes #1");
 if(out)await page.screenshot({path:path.join(out,"pr-draft-desktop.png"),fullPage:true,animations:"disabled"});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(out)await page.screenshot({path:path.join(out,"pr-draft-mobile.png"),fullPage:true,animations:"disabled"});
 await page.getByRole("button",{name:"Save PR draft"}).click();await expect(page.getByRole("heading",{name:"Correct addition for negative operands"})).toBeVisible();
 expect(saves).toBe(1);expect(submits).toBe(0);await expect(approve).not.toBeChecked();await expect(submit).toBeDisabled();await approve.check();await submit.click();expect(submits).toBe(1);
});
