import type { Icon, IconProps } from "@phosphor-icons/react";
import { PulseIcon } from "@phosphor-icons/react/dist/csr/Pulse";
import { ArrowUpRightIcon } from "@phosphor-icons/react/dist/csr/ArrowUpRight";
import { ArrowRightIcon } from "@phosphor-icons/react/dist/csr/ArrowRight";
import { ArrowLeftIcon } from "@phosphor-icons/react/dist/csr/ArrowLeft";
import { ArrowUpIcon } from "@phosphor-icons/react/dist/csr/ArrowUp";
import { CpuIcon } from "@phosphor-icons/react/dist/csr/Cpu";
import { CaretRightIcon } from "@phosphor-icons/react/dist/csr/CaretRight";
import { QuestionIcon } from "@phosphor-icons/react/dist/csr/Question";
import { DiamondsFourIcon } from "@phosphor-icons/react/dist/csr/DiamondsFour";
import { GitBranchIcon } from "@phosphor-icons/react/dist/csr/GitBranch";
import { SquaresFourIcon } from "@phosphor-icons/react/dist/csr/SquaresFour";
import { ListIcon } from "@phosphor-icons/react/dist/csr/List";
import { ChatsCircleIcon } from "@phosphor-icons/react/dist/csr/ChatsCircle";
import { MoonStarsIcon } from "@phosphor-icons/react/dist/csr/MoonStars";
import { SunIcon } from "@phosphor-icons/react/dist/csr/Sun";
import { CompassIcon } from "@phosphor-icons/react/dist/csr/Compass";
import { GearSixIcon } from "@phosphor-icons/react/dist/csr/GearSix";
import { ShieldCheckIcon } from "@phosphor-icons/react/dist/csr/ShieldCheck";
import { SlidersHorizontalIcon } from "@phosphor-icons/react/dist/csr/SlidersHorizontal";
import { StackIcon } from "@phosphor-icons/react/dist/csr/Stack";
import { XIcon } from "@phosphor-icons/react/dist/csr/X";
import { ChartBarIcon } from "@phosphor-icons/react/dist/csr/ChartBar";
import { CheckCircleIcon } from "@phosphor-icons/react/dist/csr/CheckCircle";
import { PauseCircleIcon } from "@phosphor-icons/react/dist/csr/PauseCircle";
import { ArrowsDownUpIcon } from "@phosphor-icons/react/dist/csr/ArrowsDownUp";
import { GitPullRequestIcon } from "@phosphor-icons/react/dist/csr/GitPullRequest";
import { MagnifyingGlassIcon } from "@phosphor-icons/react/dist/csr/MagnifyingGlass";
import { ArrowClockwiseIcon } from "@phosphor-icons/react/dist/csr/ArrowClockwise";
import { ArrowCounterClockwiseIcon } from "@phosphor-icons/react/dist/csr/ArrowCounterClockwise";
import { CheckIcon } from "@phosphor-icons/react/dist/csr/Check";
import { ArrowElbowDownLeftIcon } from "@phosphor-icons/react/dist/csr/ArrowElbowDownLeft";
import { CircleDashedIcon } from "@phosphor-icons/react/dist/csr/CircleDashed";
import { ArrowSquareOutIcon } from "@phosphor-icons/react/dist/csr/ArrowSquareOut";
import { CopyIcon } from "@phosphor-icons/react/dist/csr/Copy";
import { TerminalWindowIcon } from "@phosphor-icons/react/dist/csr/TerminalWindow";
import { ClockIcon } from "@phosphor-icons/react/dist/csr/Clock";
import { DesktopIcon } from "@phosphor-icons/react/dist/csr/Desktop";
import { FolderOpenIcon } from "@phosphor-icons/react/dist/csr/FolderOpen";
import { GithubLogoIcon } from "@phosphor-icons/react/dist/csr/GithubLogo";

// Individual imports keep the development bundle small. Icons are decorative by default.
function duotone(Component: Icon) {
  return function AppIcon(props: IconProps) {
    return (
      <Component size={20} weight="duotone" aria-hidden="true" {...props} />
    );
  };
}
export const Activity = /* @__PURE__ */ duotone(PulseIcon);
export const ArrowUpRight = /* @__PURE__ */ duotone(ArrowUpRightIcon);
export const ArrowRight = /* @__PURE__ */ duotone(ArrowRightIcon);
export const ArrowLeft = /* @__PURE__ */ duotone(ArrowLeftIcon);
export const ArrowUp = /* @__PURE__ */ duotone(ArrowUpIcon);
export const Bot = /* @__PURE__ */ duotone(CpuIcon);
export const ChevronRight = /* @__PURE__ */ duotone(CaretRightIcon);
export const CircleHelp = /* @__PURE__ */ duotone(QuestionIcon);
export const Command = /* @__PURE__ */ duotone(DiamondsFourIcon);
export const GitBranch = /* @__PURE__ */ duotone(GitBranchIcon);
export const LayoutDashboard = /* @__PURE__ */ duotone(SquaresFourIcon);
export const Menu = /* @__PURE__ */ duotone(ListIcon);
export const MessageSquare = /* @__PURE__ */ duotone(ChatsCircleIcon);
export const Moon = /* @__PURE__ */ duotone(MoonStarsIcon);
export const Sun = /* @__PURE__ */ duotone(SunIcon);
export const Radar = /* @__PURE__ */ duotone(CompassIcon);
export const Settings = /* @__PURE__ */ duotone(GearSixIcon);
export const ShieldCheck = /* @__PURE__ */ duotone(ShieldCheckIcon);
export const SlidersHorizontal = /* @__PURE__ */ duotone(SlidersHorizontalIcon);
export const Sparkles = /* @__PURE__ */ duotone(StackIcon);
export const X = /* @__PURE__ */ duotone(XIcon);
export const Zap = /* @__PURE__ */ duotone(ChartBarIcon);
export const CircleCheck = /* @__PURE__ */ duotone(CheckCircleIcon);
export const CirclePause = /* @__PURE__ */ duotone(PauseCircleIcon);
export const ArrowDownUp = /* @__PURE__ */ duotone(ArrowsDownUpIcon);
export const GitPullRequest = /* @__PURE__ */ duotone(GitPullRequestIcon);
export const Search = /* @__PURE__ */ duotone(MagnifyingGlassIcon);
export const RefreshCw = /* @__PURE__ */ duotone(ArrowClockwiseIcon);
export const RotateCcw = /* @__PURE__ */ duotone(ArrowCounterClockwiseIcon);
export const Check = /* @__PURE__ */ duotone(CheckIcon);
export const CornerDownLeft = /* @__PURE__ */ duotone(ArrowElbowDownLeftIcon);
export const CircleDashed = /* @__PURE__ */ duotone(CircleDashedIcon);
export const ExternalLink = /* @__PURE__ */ duotone(ArrowSquareOutIcon);
export const Copy = /* @__PURE__ */ duotone(CopyIcon);
export const Terminal = /* @__PURE__ */ duotone(TerminalWindowIcon);
export const Clock = /* @__PURE__ */ duotone(ClockIcon);
export const Monitor = /* @__PURE__ */ duotone(DesktopIcon);
export const Folder = /* @__PURE__ */ duotone(FolderOpenIcon);
export const Github = /* @__PURE__ */ duotone(GithubLogoIcon);
