package execution

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"forgeflow/internal/codex"
	"forgeflow/internal/domain"
	"forgeflow/internal/github"
	"forgeflow/internal/storage"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

func TestPublicPRTextSeparatesAuditAndTechnicalSubjects(t *testing.T) {
	a := domain.WorkspaceApproval{Opportunity: domain.Opportunity{Number: 7, Title: "Fix LLM API retries"}}
	r := domain.ExecutionRecord{Summary: "Fix request cancellation.\nBuilt using an LLM.", Report: "Codex model: private-model", ChangedFiles: []string{"retry.go"}, Plan: &domain.Plan{Risks: []string{"Remote failures remain possible."}}}
	tests := []domain.TestRun{{Command: domain.VerificationCommand{Program: "go", Arguments: []string{"test", "./..."}}, ExitCode: 1, FinishedAt: time.Now()}, {Command: domain.VerificationCommand{Program: "go", Arguments: []string{"test", "./..."}}, ExitCode: 0, FinishedAt: time.Now()}}
	title, body := publicPR(a, r, tests)
	if !strings.Contains(title, "LLM API") || strings.Contains(body, "private-model") || strings.Contains(body, "exit 1") || !strings.Contains(body, "exit 0") {
		t.Fatalf("incorrect public draft: %s %s", title, body)
	}
	if err := validatePRText(title, body); err != nil {
		t.Fatal(err)
	}
	for _, claim := range []string{"This PR was generated by ChatGPT", "Implemented with Codex", "AI-assisted change", "Co-authored-by: copilot[bot]"} {
		if validatePRText("Fix", claim) == nil {
			t.Fatalf("attribution accepted: %s", claim)
		}
	}
	if r.Report != "Codex model: private-model" {
		t.Fatal("internal audit changed")
	}
}

type panicRunner struct{ fixtureRunner }

func (*panicRunner) Run(context.Context, codex.Request, func(json.RawMessage) error) (codex.Result, error) {
	panic("fixture panic")
}
func TestWorkerPanicPreservesEvidenceAndReleasesTask(t *testing.T) {
	s, c := buildFixture(t, &panicRunner{})
	ctx := context.Background()
	if _, err := s.Start(ctx, c.ID, true, false); err != nil {
		t.Fatal(err)
	}
	s.Wait()
	r, err := s.Store.Execution(ctx, c.ID)
	if err != nil || r.Status != "BLOCKED" {
		t.Fatalf("panic not isolated: %+v %v", r, err)
	}
	agents, err := s.Store.Agents(ctx)
	if err != nil || len(agents) != 1 || agents[0].Status != "FAILED" || agents[0].FinishedAt == nil {
		t.Fatalf("stale agent: %+v %v", agents, err)
	}
	if err = s.beginPR(c.ID); err != nil {
		t.Fatal("task was not released", err)
	}
	s.endPR(c.ID)
}
func TestOperationsCannotRaceOrMutateOnFailedRetry(t *testing.T) {
	s, c := buildFixture(t, &fixtureRunner{})
	ctx := context.Background()
	before, _ := s.Store.Contribution(ctx, c.ID)
	s.tasks[c.ID] = &task{}
	if err := s.beginPR(c.ID); err == nil {
		t.Fatal("PR raced execution")
	}
	delete(s.tasks, c.ID)
	if err := s.beginPR(c.ID); err != nil {
		t.Fatal(err)
	}
	if err := s.Control(ctx, c.ID, "abandon", true); err == nil {
		t.Fatal("control raced PR")
	}
	if _, err := s.Retry(ctx, c.ID, "tests", true); err == nil {
		t.Fatal("retry raced PR")
	}
	s.endPR(c.ID)
	after, _ := s.Store.Contribution(ctx, c.ID)
	if before.State != after.State {
		t.Fatal("failed action changed contribution")
	}
	cancelled, cancel := context.WithCancel(ctx)
	cancel()
	s.ctx = cancelled
	if err := s.beginPR(c.ID); err == nil {
		t.Fatal("PR started during shutdown")
	}
}
func TestPRDraftRevisionAndPreparedApproval(t *testing.T) {
	s, c := buildFixture(t, &fixtureRunner{})
	ctx := context.Background()
	r := domain.ExecutionRecord{ContributionID: c.ID, Status: "PR_PREPARED", PRTitle: "Fix addition", PRBody: "Fixes #1", HeadCommit: strings.Repeat("a", 40)}
	r.SubmissionToken = submissionToken(r)
	if err := s.Store.SaveExecutionCheckpoints(ctx, r, []string{"PLANNING", "CODING", "TESTING", "REVIEWING", "READY", "PR_PREPARED"}, "fixture", "ready"); err != nil {
		t.Fatal(err)
	}
	edited, err := s.SavePRText(ctx, c.ID, "Correct addition", "Regression test passed. Fixes #1", PRRevision(r))
	if err != nil {
		t.Fatal(err)
	}
	if edited.SubmissionToken == r.SubmissionToken {
		t.Fatal("old approval retained")
	}
	if _, err = s.SavePRText(ctx, c.ID, "Stale", "Stale", PRRevision(r)); !errors.Is(err, storage.ErrConflict) {
		t.Fatal("stale draft overwrite accepted", err)
	}
	if _, err = s.SubmitPR(ctx, c.ID, r.SubmissionToken, true); err == nil {
		t.Fatal("old approval accepted")
	}
	if _, err = s.SavePRText(ctx, c.ID, "Fix", "Generated by an LLM", PRRevision(edited)); err == nil {
		t.Fatal("authorship accepted")
	}
}
func TestPRSubmissionRecoversAcceptedRemoteRequestWithoutWrites(t *testing.T) {
	s, c := buildFixture(t, &fixtureRunner{})
	ctx := context.Background()
	repo, _, _ := s.Paths(c)
	sha, err := s.git(ctx, repo, "rev-parse", "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	r := domain.ExecutionRecord{ContributionID: c.ID, Status: "PR_PREPARED", PRTitle: "Fix addition", PRBody: "Fixes #1", HeadCommit: strings.TrimSpace(sha)}
	r.SubmissionToken = submissionToken(r)
	if err = s.Store.SaveExecutionCheckpoints(ctx, r, []string{"PLANNING", "CODING", "TESTING", "REVIEWING", "READY", "PR_PREPARED"}, "fixture", "ready"); err != nil {
		t.Fatal(err)
	}
	writes, issueReads := 0, 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.Method != "GET" {
			writes++
			http.Error(w, "unexpected write", 500)
			return
		}
		if req.URL.Path == "/user" {
			fmt.Fprint(w, `{"login":"contributor"}`)
			return
		}
		if strings.HasSuffix(req.URL.Path, "/pulls") {
			if req.URL.Query().Get("state") != "all" {
				t.Error("closed PR recovery missing")
			}
			json.NewEncoder(w).Encode([]any{map[string]any{"html_url": "https://github.com/example/fixture/pull/9", "title": r.PRTitle, "body": r.PRBody, "head": map[string]string{"sha": r.HeadCommit}, "base": map[string]string{"ref": "main"}}})
			return
		}
		issueReads++
		http.Error(w, "issue already closed", 404)
	}))
	defer server.Close()
	s.Client = github.New("fixture-token")
	s.Client.BaseURL = server.URL
	recovered, err := s.SubmitPR(ctx, c.ID, r.SubmissionToken, true)
	if err != nil || recovered.Status != "PR_OPENED" || writes != 0 || issueReads != 0 {
		t.Fatalf("recovery failed: %+v %v writes=%d reads=%d", recovered, err, writes, issueReads)
	}
}
